### ISSUE TITLE
Gradle workflow unable to build after Java version update

### ISSUE THREAD

**Issue by Benji377** [Benji377/OpenMusic#226]
Gradle isn't building the project after updating the Android version from 1.8 to 11
Issue:
```
...\OpenMusic\app\src\main\java\com\musicplayer\OpenMusic\utils\ImportExportUtils.java:13: error: cannot find symbol
import org.json.XML;
               ^
  symbol:   class XML
  location: package org.json
  ```

**Comment by Benji377** [comment]
A solution might be to download the jar and include it manually

**Comment by Benji377** [comment]
Referencing this Stackoverflow issue: https://stackoverflow.com/questions/33050846/can-not-use-class-org-json-xml-on-android-studio

**Comment by Benji377** [comment]
A possible solution might be to follow the instructions mentioned here: https://stackoverflow.com/a/36797613

Use this package: https://developer.android.com/reference/javax/xml/package-summary

**Comment by Benji377** [comment]
Fixed issue using the GitHub library: https://github.com/smart-fun/XmlToJson
